---
title: "Working Notes"
date: "`r format(Sys.time(), '%b %d, %Y')`"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
Items to get help on:  

##General/Site-Wide:

+  Write bibliographic entries for missing citations. 
+  Set menu so landing page of each topic is an "Overview"
+  Modify bottom code of all pages. If has citations, make sure the page has:
```
      #### \   
      ***
```
+  If a page has no citations, REMOVE the bottom code for the horizontal rule. It now is in the footer.
+  Beloe is the standard output format for citation tags in my copy of BibDesk. To make the tags work properly, need to search and replace the pre-string.

```\@[Carpenter2001] is output. Change "\@[" to "[@"```

##Index:
*  Decide on bottom page site map strategy, and attach.  

##Background:
*  Need to finish these pages:  
    +  Df
    +  Df

##Lit review:  
*  Finalize what content pages will be
    +  Df  

##The Build:
*  Find out from Melissa which method/model she is using. Useful for another project.  
    +  Df  
    

##Data Exploration:
*  Try fixing problem of aligning tables and keeping the NA values by switching from "merge" to "full_join"  
*  Try modifying the comparison of word frequencies in all comments vs. subgroups to comparison between two subsamples from full group. How do the individual subgroups compare to a random sample? Is the variation I see just noise?  
*  For N-gram analysis, how to join tables with missing values?
    +  Use full_join, not merge. 

##Findings:
*  How to graph the different comparisons of NB values from different sources on same plot? 
    +  Add ggplot (data=) value. SOLVED 
    +  Better to combine data into one dataset though. (REQUIRED for proper legend formats)

#Next Steps:
*  Still in draft stage
    +  Df  

#Etc.:
*  Adding the Bibliography in this format
    +  Need to add the new citation entries to library.bib
*  Adding automatic updates to top dates? 
    +  ```date: "`r format(Sys.time(), '%b %d, %Y')`" ```

#Miscellaneous:
*  Fix GitHub link on laptop to auto-upload without passwords again

##Try These Out:
*  Use Mike's Metadata packager to annotate our released dataset
*  Use ```mutate(datacolumn=str_count(utterance_clean, "\\b(um|u=m)\\b"))``` to extract a string character and count. Use this to count punctuation only comments, or ID comments with questions.

####\  

