# R Code
#### I can write code for Shiny and build pages locally, but they do not build for a website. 
The build stalls here, with the error message:

>label: unnamed-chunk-1 (with options) 
>List of 1  
> $ echo: logi FALSE  
>Error in selectInput("n_breaks", label = "Number of bins:", choices = c(10,  :   
>  could not find function "selectInput"  
>Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval  
>Execution halted  
>Exited with status 1.

Ideas?


-----

# Project

-----

# Github
#### When I work on Github, I see no easy way to create new file folders. 

If I empty a folder, it is deleted automatically. Am I overlooking tools, or is goal to be working locally to create files and use web interface less often? 

-----

#### I am not sure how to clone and blend my OWN repos. 
I was trying to build a starting point with both data code and web site pieces by cloning the web site repo, then adding the standard data layout folder. Could not see an obvious way to clone one of my own, or to blend two into one.

-----

#### Still not sure I know difference between a fork and a branch. 
Branch is an alternative version of a single file, but fork is a copy of the original repo in total. Y/N?

-----

#### Can I build multiple files in R, then push project to GitHub as a complete repo?
Yep. Found instructions for doing it on this website.
https://cfss.uchicago.edu/git05.html

Is this correct, that if need be, I could download a ZIP of a project from someone else, unpack in my local machine (Dropbox, actually), then upload back to GitHub just the same as if I cloned it directly inside GH?

I know it is the long way around, but if I have a folder of resources someone gives me, it seems rude to ask, "can you put that on GitHub first for me?"

So how do I tell R to use my GitHub repo's as their source for data?

-----

#### Having a slight problem with Git on laptop.
I can use my desktop and create repos to Dropbox or local machine from GitHub. Laptop throws in an extra step that seems to corrupt process.

**SOLVED**. The path to Git was wrong. Needs to be very specific: 
/usr/local/git/bin/git

Other Git and Git-GUI paths do not work.
