# Question
#### When I write to the Master, I am writing to the forked copy of this website, correct? 
So if that is correct, and Mike is still listed as a collaborator:
Are MY edits being kept here until I send a Pull/Push request?
My edits only affect this repo, correct?

# Question
#### Anyone else need a QUICK tour of the branch and pull request map?

# Question
#### Still unclear on difference between a fork and a branch. 
Branch is an alternative version of a single file, but fork is a copy of the original repo in total. Y/N?

# Question
#### When I am working in my own repo, does it propagate? How do I connect to it in R?
When I created my default website repo via fork, I assume I can edit that to my liking, and it will not be propagated back to whomever I forked it from. I also can presumably download a ZIP of a repo and install it to my local machine (Dropbox, actually). 

So how do I tell R to use my GitHub repo's as their source for data?

# Question
#### Having a slight problem with Git on laptop.
I can use my desktop and create repos to Dropbox or local machine from GitHub. Laptop throws in an extra step that seems to corrupt process.
