---
title: "The Challenges of Teaching Technical Writing"
date: "`r format(Sys.time(), '%b %d, %Y')`"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
Strong scientific thinking & communication skills are essential for 21st century STEM workers [@Anderman2011, @CWPA2011, @PCAST2012], but there are not enough college graduates with these skills to meet projected US workforce demands [@AACU2007, @BHEF2011, @Carnevale2011]. Policy makers have called on educators to prioritize development of "career-relevant 21st-century skills” [@CWPA2011, @NRC2010, @NRC2012, @Starke-Meyerring2011]. These include quantitative and information literacy, adaptability, novel problem-solving, self-regulation, systems thinking, analytical and critical thinking skills, and complex communication skills [@Anderman2011] A more scientifically and computationally literate citizenry also will be better prepared to evaluate personal choices, societal issues, and larger policies that have deep connections to science and technology [@PCAST2012].

All of the aforementioned 21st-century skills are vital for college graduates, so why focus specifically on improving written communication in the form of scientific writing? First, these skills do not develop in isolation. As students master complex communication, they also develop critical thinking skills [@Anderman2011, @Carpenter2001, @Gorzelski2016, @Rounsaville2008, @Reiff2011, @Rogers2011, @Starke-Meyerring2011, @White2009]. By improving written communication we also can impact other skills. Second, good communication skills cut across all STEM fields. Even individuals working in relative isolation routinely record data and observations, interpret evidence, and share findings informally or formally either orally or in writing. Scientific writing skills are also valued and highly sought by employers independent of discipline or field of study [@Treadwell1999, @Gray2005, @Fry2014]. Third, writing is not just a mean for communication. It is also a tool to teach and develop scientific thinking. Scientific writing proficiency helps students be more literate and focused, and move from intuition-based thinking towards evidence-based thinking [@Libarkin2012, @Quitadamo2007, @Fellows1994]. 

Given projected workforce needs and that strong communications skills are vital across the range of careers, teaching scientific writing should be an obvious priority in STEM courses. Ideally, instructors would give students regular opportunities to practice critical and applied thinking by assigning writing routinely [@Reynolds2012, @Holyoak1998, @Anderman2011], but there are significant logistical barriers to this pedagogical ideal [@Haswell2006a, @Haswell2006b, @Henderson2007]. 

The most obvious logistical barrier is workload. Good scientific writing is one of the most difficult and time-consuming skills to teach. It is an iterative cycle of writing drafts, receiving actionable feedback and coaching, then making further refinements until a final product emerges. This cycle is too time- and labor-intensive to be practical in high-enrollment introductory courses. Even in lower-enrollment courses with more than 10-20 students, multiple assignments pose significant logistical challenges [@Coil2010, @Fry2014]. When students do have an opportunity to write for class, circumstances may permit just one round of revisions. The feedback they receive needs to be as focused, individualized, and impactful as possible. 

Giving effective feedback is a challenging and complex task that needs to be learned through specific training [@Bazerman1994, @Bazerman2006, @Gottschalk2003, @Graves2011, @Kiefer2002, @NCTENWP, @Perelman2009, @Szymanski2014, @Underwood2006]. Effective feedback will be process-oriented rather than focused on finding and correcting errors. Comments will be understandable and unambiguous. Effective feedback keeps the writer in control and encourages them to revise their draft thoughtfully and thoroughly, and keeps copy-editing feedback to a minimum [@Breidenbach2006, @Ruegg2015, @Trupiano2006]. Over-commenting or giving overly prescriptive comments can push a student writer into a passive role. They treat comments as a to-do list that needs to be completed rather than suggestions for reflection and self-assessment [@Anson2001, @CWPA2011, @Harris1979, @Haswell2006a, @Haswell2006b, @Reynolds2009, @Szymanski2015, @Swilky1991, @Underwood2006]. 

There is clear need for more robust student training and assessment models that make it easier to give students multiple cycles of “holistic feedback,” that is, feedback that helps undergraduates identify their current shortcomings as a writer and directs them towards a path to improvement. An ideal model would: 1) embody best practices for teaching writing; 2) reduce instructor workload; 3) stress holistic feedback rather than copy-editing; 4) limit the overall number of comments to what students can manage; and 5) help students understand feedback and prioritize revision efforts appropriately. 

####\  

#Faculty Need Training to Teach Technical Writing Well
This project focuses specifically on improving the feedback process in two ways. First, the training program teaches instructors how to give holistic feedback that is individualized and context-specific. Second, students will receive a portion of their feedback from SAWHET, a technology-assisted, automated feedback system. 

A major barrier to routine writing in STEM is limited instructor awareness of evidence-based training models. Many college STEM teachers have not been introduced to proven writing training strategies or trained to give effective, context-specific feedback [@Coil2010]. Policymakers are calling for faculty development programs that specifically address STEM education priorities [@NRC2010, @NRC2012, @Starke-Meyerring2011] including development of faculty across career stages and preparation of doctoral students and postdocs to be effective teachers. This needs to include how to teach science writing.

Knowing which instructional models are effective is not sufficient to ensure adoption. Faculty may have different priorities or hindering attitudes by the time they teach their first classes as assistant professors. These attitudes underlie comments like “I don’t have time for something new,” “I don’t have spare class time to spend teaching writing,” or “students should learn how to write elsewhere” [@Coil2010, @Clughe2012, @FSSE2016]. These attitudes are very resistant to change. For example, despite a nationwide multi-year effort promoting interactive, inquiry- and skills-centric teaching, many faculty still believe their main goal should be content delivery, not development of students’ disciplinary thinking and process skills [@DAvanzo2013, @Freeman2014, @Gottschalk2003, @NRC2012, @VandC2011, @FSSE2016].

Even when faculty are motivated to innovate, how they learn about alternative strategies affects the odds of adoption. For example, faculty who attend formal professional development activities that promote evidence- based practices are less likely to adopt those practices than if they learn about them from trusted colleagues or respected opinion leaders [@Andrews2016]. In contrast, graduate students who participate in formal professional development about learner-centered instruction readily adopt learner-centered methods into their personal teaching practice [@Ebert-May2015]. A more effective strategy for changing faculty instructional practices may be to target and train future faculty ([@Tanner2006] and references therein) who then act as change agents.

A central goal of this project is to test a scalable model for teaching GTAs about the importance of scientific writing in students’ intellectual development and training them to use best-practice models. Specifically, TAs will learn how to: 1) lead students through the instructional process, 2) use validated methods and rubrics, 3) provide effective, growth-oriented feedback, and 4) grade consistently. One of the questions to be tested in this project is whether GTA conceptual knowledge and self-efficacy related to teaching scientific writing training will increase over the course of the program described in Project Activities.

####\  
***
